---

- name: Install tcpdump
  apt:
    name: tcpdump
    update_cache: yes

- name: Create log folder
  file:
    path: /var/log/tcpdump
    state: directory

- import_tasks: apparmor.yml
  when: tcpdump_apparmor_complain

- name: Install the systemd service
  template:
    src: tcpdump.service.j2
    dest: /etc/systemd/system/tcpdump.service
  notify: restart tcpdump
